# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aktiviteter',
            table='Aktiviteter',
        ),
    ]
