# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160503_1950'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aktiviteter',
            table='Aktivitet',
        ),
    ]
