# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160503_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktiviteter',
            options={'verbose_name': 'Aktivitet', 'verbose_name_plural': 'Aktiviteter'},
        ),
        migrations.AlterModelTable(
            name='aktiviteter',
            table=None,
        ),
    ]
