# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160503_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktiviteter',
            options={'verbose_name': 'Aktiviteter', 'verbose_name_plural': 'Aktiviteter'},
        ),
    ]
